#!/usr/bin/env python
import os, re
import simplejson
from subprocess import check_call, CalledProcessError

# get some information about the test
modelname = raw_input("modelname=")
path = raw_input("path=")
directory = path

# from here on out, we will be in the test's directory
os.chdir(directory)

#=========================================================
# now, we check that the
# 1. executable builds
#==========================================================
title = "Build model"
critical = True
passed = True
msg = ""
warn = ""

def fail(reason):
    global msg, passed
    passed = False
    msg += reason+"\n"

try:
    check_call("make")
except CalledProcessError as e:
    fail("Could not build: %r" % e)

results = {"pass": passed, "message": msg, "warn": warn, "critical": critical, "title": title}
print "\n"+simplejson.dumps(results)
