import os, re, glob, sys
import string
import shutil
import tempfile
import datetime
import simplejson
from contextlib import nested

def CreateMetaData(name, oldname, driver):
    dic = {"kim_code": name, "title": oldname, "is_model_param": True, 
           "test_drivers": [driver], "reference": "", "disclaimer": "",
           "description": "Lattice constant tests generated by Python using ASE & openkim-python",
           "license": "NONE", "uploaded_by": "alexalemi@gmail.com",
           "created_at": datetime.datetime.now().isoformat(), "updated_at": None}
    simplejson.dump(dic, open("metadata.json", "w"))


def InFileTextReplacement(filename, oldtxt, newtxt):
    tmpfile = ""
    with nested(open(filename, "r"), tempfile.NamedTemporaryFile("w", delete=False)) as (f,o):
        data = f.read()
        o.write( re.sub(oldtxt, newtxt, data) )
        tmpfile = o.name
    shutil.move(tmpfile, filename)


def ConvertName(src, dst, driver, replacements=None):
    replacements = replacements or {}
    shutil.move(src, dst)                   #os.system("mv %s %s" % (src, dst))  #mv $head $to
    os.chdir(dst)                           #os.system("cd %s" % dst)            #cd $to
    for f in glob.glob("./%s*" % src):      # for file in `ls $head*`; do
        newf = string.replace(f, src, dst)  # newf=`echo $f|sed -e s/$head/$to/`
        shutil.move(f, newf)                # mv $f $newf
    for f in glob.glob("./*"):              # for f in `ls *`; do
        InFileTextReplacement(f, src, dst)
        for key,val in replacements.iteritems():
            InFileTextReplacement(f, key, val)
    CreateMetaData(dst, src, driver)
    os.chdir("..")


def ConvertBatch(prefix, outprefix, driver):
    index = 0
    for f in glob.glob("%s*" % prefix):
        outname = outprefix+"%03d_000" % index
        ConvertName(f, outname, driver) 
        index = index + 1


