#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2012, Regents of the University of Minnesota.  All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#    Ellad B. Tadmor
#    Valeriu Smirichinski
#


MODEL_DRIVER_NAME   := TB_FinnisSinclair_F__MD_669576659798_000
MODEL_NAME	    := TB_FinnisSinclair_F_Fe__MO_893964701445_000
SPECIES_001_NAME    := Fe
PARAM_FILE_001_NAME := $(strip $(MODEL_NAME)).params

# No changes should be needed below this line.

ifndef KIM_API_DIR
   include $(KIM_DIR)/KIM_API/Makefile.Model_Drivers
else
   include $(KIM_API_DIR)/Makefile.Model_Drivers
endif
