#!/usr/bin/python
from subprocess import Popen, PIPE, STDOUT
inputs = 2

cmds = []
exe  = raw_input()
for i in range(inputs):
    line = raw_input()
    cmds.append(line)

process = Popen(exe, shell=False, stdin=PIPE, stdout=PIPE, stderr=STDOUT)
for cmd in cmds:
    process.stdin.write(cmd+"\n")
print process.communicate()[0]
