#!/bin/bash

_getall(){
    . /pipeline/environment
    folders=$1
    part=$2
    if [ -n "$part" ]; then
        here=$(find ./ -maxdepth 1 -name "$part*" -printf "%f ")
        if [ -n "$here" ]; then
            echo "$here"
            exit 0
        fi
    fi
    
    for folder in ${folders}; do
        if [ ! -n "$part" ]; then
            temp=$(find $REPODIR/$folder/* -maxdepth 1 -type d -printf "%f ")
            echo $temp
        else
            temp=$(find $REPODIR/$folder/* -maxdepth 1 -type d -name "$part*" -printf "%f ")
            echo $temp
        fi
    done
}

_pipeline_complete() 
{
    . /pipeline/environment
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # The basic options we'll complete.
    opts="director worker site"

    # Complete the arguments to some of the basic commands.
    case "${prev}" in
        site)
            local objs=$(_getall "te td mo md" "$cur") 
            COMPREPLY=( $(compgen -W "${objs}" -- ${cur}) )
            return 0
            ;;
        *)
            ;;
    esac

    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))  
    return 0
}

_kimitems_complete() 
{
    . /pipeline/environment
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # The basic options we'll complete.
    opts="install download search remove"

    # Complete the arguments to some of the basic commands.
    case "${prev}" in
        remove)
            local objs=$(_getall "te td mo md" "$cur") 
            COMPREPLY=( $(compgen -W "${objs}" -- ${cur}) )
            return 0
            ;;
        *)
            ;;
    esac

    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))  
    return 0
}

_pipeline_complete_folders() 
{
    . /pipeline/environment
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    FOLDERS=$1

    # Complete the arguments to some of the basic commands.
    case "${prev}" in
        *)
            local objs=$(_getall "$FOLDERS" "$cur")
            COMPREPLY=( $(compgen -W "${objs}" -- ${cur}) )
            return 0
            ;;
        *)
            ;;
    esac

    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))  
    return 0
}

_complete_pipeline(){
    _pipeline_complete
}

_complete_kimitems(){
    _kimitems_complete
}

_complete_pipeline_all(){
    _pipeline_complete_folders "te td mo md"
}

_complete_pipeline_td(){
    _pipeline_complete_folders "td"
}

complete -F _complete_pipeline     pipeline
complete -F _complete_kimitems     kimitems
complete -F _complete_pipeline_td  testgenie
complete -F _complete_pipeline_all pipeline_runpair
complete -F _complete_pipeline_all pipeline_runmatches
complete -F _complete_pipeline_all pipeline_verify
