#! /usr/bin/env python
""" Allows us to dump whats in the tubes """

import os
import sys
import beanstalkc as bean
from pipeline.network import BeanstalkConnection 
from pipeline.config import *

beanc = BeanstalkConnection()
beanc.connect()

usual_channels = ["errors","results","logs"]
full_channels = ["web_updates", "jobs","results","updates","errors","logs"]

def dump_channel(channel):
    print "dumping channel:", channel
    try:
        stats = beanc.bsd.stats_tube(channel)
    except bean.CommandFailed:
        print "No tube: ", channel
        return

    job_number = stats['current-jobs-ready']

    with open(os.path.join(KIM_LOG_DIR,channel),'a') as fl:
        for i in xrange(job_number):
            beanc.bsd.watch(channel)
            j = beanc.bsd.reserve()
            fl.write(j.body)
            print "dumping message: ", j.body
            fl.write('\n')
            j.delete()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        for channel in full_channels:
            dump_channel(channel)
    else:
        for channel in usual_channels:
            dump_channel(channel)
