#!/usr/bin/env python
import database
import kimobjects
from compute import Computation
import sys
from config import *
from logger import logging
from pipeline import Director
logger = logging.getLogger("pipeline").getChild("development")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=
        """A utility to run a runner (Test, Verification check) against
        a particular subject (Model, Test).  This utility operates through
        the pipeline APIs and as such emulates pipeline runtime behavior."""
    )
    parser.add_argument('runner-name', type=str,
        help="The KIM code of the runner. Can be a test or verification check.")
    parser.add_argument('subject-name', type=str,
        help="KIM code for the subject which can be a model or test.")
    parser.add_argument('-i', '--inplace', action='store_true', default=False,
        help="""Run the test in the runner's absolute directory instead of a 
        temporary working directory and copying the results to the result folder""")
    args = vars(parser.parse_args())

    runner = kimobjects.kim_obj(args['runner-name'])
    subject = kimobjects.kim_obj(args['subject-name'])
    logger.info("Running combination <%r, %r" % (runner, subject))
    
    if not args['inplace']:
        d = Director()
        Computation(runner, subject, d.get_result_code()).run()
    else:
        Computation(runner, subject).run()
