#!/usr/bin/env python
import sys
import kimquery
from config import *
from logger import logging
logger = logging.getLogger("pipeline")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        name = sys.argv[1]
    else:
        name = "results.edn"

    reply = kimquery.query_property_validator(name)

    try:
        re.match(r"Errors", reply).groups()
        logger.error("\n"+reply)
    except AttributeError:
        logger.info("\n"+reply)
