#!/usr/bin/env python
import sys
import pprint
import kimquery
import json
from config import *
from logger import logging
from compute import test_result_valid
logger = logging.getLogger("pipeline")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        name = sys.argv[1]
    else:
        name = "results.edn"

    valid, reply = test_result_valid(name)
    if valid:
        logger.info("Test result valid")
    else:
        logger.error("Test result invalid")
        print json.dumps(reply, indent=4)
