#!/usr/bin/env python
from logger import pygmentize

if __name__ == "__main__":
    import sys
    if len(sys.argv) == 2:
        if sys.argv[1] == "help":
            print """
            Usage:
                pipeline_pygmentize <input_file>
                stdin | pipeline_pygmentize 
            """
        else:
            with open(sys.argv[1], 'r') as toparse:
                for line in toparse:
                    pygmentize(line)
    else:
        for line in sys.stdin:
            pygmentize(line)
