#!/usr/bin/env python
import database
import kimobjects
from compute import Computation
import sys
from config import *
from logger import logging
from pipeline import Director
logger = logging.getLogger("pipeline").getChild("development")

if __name__ == "__main__":
    if len(sys.argv) == 3:
        d = Director()
        testname = sys.argv[1]
        modelname = sys.argv[2]

        name,leader,num,version = database.parse_kim_code(testname)


        test = kimobjects.Test(testname)
        model = kimobjects.Model(modelname)

        logger.info("Running %r against %r", testname, modelname)
        comp = Computation(test,model,d.get_result_code())
        comp.run()

    else:
        logger.info("Usage: pipeline_run <testname> <modelname>")
