#!/usr/bin/env python
import database
import kimobjects
import runner
import sys
from config import *

if __name__ == "__main__":
    if len(sys.argv) == 2:
        testname = sys.argv[1]
        name,leader,num,version = database.parse_kim_code(testname)
        if leader == "TE":
            test = kimobjects.Test(testname)
            if len(list(test.models)) > 0:
                for model in test.models:
                    logger.info("Running combination <%r, %r" % (test, model))
                    runner.run_test_on_model(test, model)
            else:
                logger.info("No matches found for your test")
        if leader == "TD":
            test = kimobjects.TestDriver(testname)
            if len(list(test.tests)) > 0:
                for t in test.tests:
                    for m in t.models:
                        logger.info("Running combination <%r, %r" % (t, m))
                        runner.run_test_on_model(t, m)
            else:
                logger.info("No matches found for your test driver")
        if leader == "MO":
            model = kimobjects.Model(testname)
            if len(list(model.tests)) > 0:
                for t in model.tests:
                    logger.info("Running combination <%r, %r" % (t, model))
                    runner.run_test_on_model(t, model)
            else:
                logger.info("No matches found for your test driver")
        if leader == "MD":
            driver = kimobjects.ModelDriver(testname)
            if len(list(driver.models)) > 0:
                for m in driver.models:
                    for t in m.tests:
                        logger.info("Running combination <%r, %r" % (t, m))
                        runner.run_test_on_model(t, m)
            else:
                logger.info("No matches found for your test driver")
    
    else:
        logger.info("Usage: debugtest.py <testname>")
