#!/usr/bin/env python
from pipeline.logger import pygmentize

helpmsg = """
Usage:
    pipeline_pygmentize <input_file>
    stdin | pipeline_pygmentize 
"""

if __name__ == "__main__":
    import sys

    if len(sys.argv) == 2:
        if (sys.argv[1] == "--help" or sys.argv[1] == "-h" or
                sys.argv[1] == "help"):
            print helpmsg
        else:
            with open(sys.argv[1], 'r') as toparse:
                for line in toparse:
                    pygmentize(line)
    else:
        for line in sys.stdin:
            pygmentize(line)
