#!/usr/bin/env python
import compute
import kimobjects
from config import *
from logger import logging
logger = logging.getLogger("pipeline")

def run_verifiers(kimobj):
   
    if isinstance(kimobj, kimobjects.Test):
        verifiers = list(kimobjects.VerificationTest.all())
    elif isinstance(kimobj, kimobjects.Model):
        verifiers = list(kimobjects.VerificationModel.all())
    else:
        return

    allpassed = []
    for v in verifiers:
        comp = compute.Computation(v, kimobj)
        try:
            comp.run()
            passed = comp.results['pass']
        except Exception as e:
            passed = False
        allpassed.append(passed) 
    return [v.kim_code for v in verifiers],allpassed

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        name = sys.argv[1]

    try:
        t = kimobjects.Test(name)
    except Exception as e:
        try:
            t = kimobjects.Model(name)
        except Exception as e:
            raise AssertionError("Could not make test or model")
    v,p = run_verifiers(t)

    logger.info("==================================================")
    logger.info("Verification check report:")
    logger.info("==================================================")
    if len(list(v)) > 0:
        maxlen = max([len(s) for s in v])
        for tv, tp in zip(v,p):
            if tp == True:
                logger.info(tv+"  " + " "*(maxlen-len(tv))+ ":\t PASS")
            else:
                logger.info(tv+"  " + " "*(maxlen-len(tv))+ ":\t ERROR")
    else:
        logger.info("ERROR: No verification checks found")

