#!/usr/bin/env python
import os

import compute
import kimobjects
from pipeline import Director
from config import *
from logger import logging
logger = logging.getLogger("pipeline")

def run_verifiers(kimobj):
    d = Director()

    if isinstance(kimobj, kimobjects.Test):
        verifiers = list(kimobjects.TestVerification.all())
    elif isinstance(kimobj, kimobjects.Model):
        verifiers = list(kimobjects.ModelVerification.all())
    else:
        return

    allpassed = []
    for v in verifiers:
        comp = compute.Computation(v, kimobj, d.get_result_code())
        try:
            comp.run()
            resultfile = os.path.join(comp.full_result_path, "results.edn")
            docs = loadedn(resultfile)
            for di in docs:
                if di.has_key('passed'):
                    passed = di['passed']
        except Exception as e:
            passed = False
        allpassed.append(passed)
    return [v.kim_code for v in verifiers],allpassed

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=
        """Utility to run all relevant verification checks for a KIM object.
        This can be run for tests and models.  A summary is printed at the
        end of testing."""
    )
    parser.add_argument('kimcode', type=str,
        help="KIM code of the object to run the verification checks")
    args = vars(parser.parse_args())
    name = args['kimcode']

    try:
        t = kimobjects.Test(name)
    except Exception as e:
        try:
            t = kimobjects.Model(name)
        except Exception as e:
            raise AssertionError("Could not make test or model object")
    v,p = run_verifiers(t)

    logger.info("==================================================")
    logger.info("Verification check report:")
    logger.info("==================================================")
    if len(list(v)) > 0:
        maxlen = max([len(s) for s in v])
        for tv, tp in zip(v,p):
            if tp == True:
                logger.info(tv+"  " + " "*(maxlen-len(tv))+ ":\t PASS")
            else:
                logger.info(tv+"  " + " "*(maxlen-len(tv))+ ":\t ERROR")
    else:
        logger.info("ERROR: No verification checks found")

