#!/bin/bash

screen -dm -S gateway     env PIPELINE_GATEWAY=1 python /home/openkim/data/openkim-pipeline/gateway.py
screen -dm -S gateway_dbg env PIPELINE_GATEWAY=1 PIPELINE_DEBUG=1 python /home/openkim/data/openkim-pipeline/gateway.py dbg
