#!/usr/bin/python
from subprocess import Popen, PIPE, STDOUT
inputs = 4

cmds = []
exe  = raw_input()
for i in range(inputs):
    line = raw_input()
    cmds.append(line)
#exe = "/home/vagrant/TD_28449590_000/TD_28449590_000"
#cmds = ["Ar", "fcc", "ex_model_Ar_P_LJ"]

process = Popen(exe, shell=False, stdin=PIPE, stdout=PIPE, stderr=STDOUT)
for cmd in cmds:
    process.stdin.write(cmd+"\n")
print process.communicate()[0]
